version: '3.5'

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

volumes:
  db-data:
    driver: local

services:
  web:
    image: nginx:1.17-alpine
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      frontend:
        ipv4_address: 192.168.0.10
      backend:
        ipv4_address: 192.168.10.11
    depends_on:
      - db
  app:
    build: ./docker/local/wordpress
    container_name: app
    volumes:
      - ./:/var/www/html
      - ./docker/local/wordpress/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    extra_hosts:
      - localhost:192.168.10.11
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      # タイムゾーンを 東京 にする
      - TZ=Asia/Tokyo
    volumes:
      - ./logs/db:/var/log/mysql
      - ./docker/local/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
      - ./docker/local/mysql/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    networks:
      - backend
