version: '3.5'

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

volumes:
  db-data:
    driver: local

services:
  web:
    image: nginx:1.17-alpine
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      frontend:
        ipv4_address: 192.168.0.10
      backend:
        ipv4_address: 192.168.10.11
    depends_on:
      - db
  app:
    image: wordpress:5.3.2-php7.4-fpm
    container_name: app
    volumes:
      - ./:/var/www/html
    networks:
      - backend
    extra_hosts:
      - localhost:192.168.10.11
    depends_on:
      - db
  db:
    build: ./docker/local/mysql
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
